### PR TITLE
Revert "Refactoring of various aspects of this directive"

### PR DESCRIPTION
**Pull request by eee-c**
Reverts eee-c/angular-bind-polymer#12

Broke some tests...

### CODE REVIEW

**Comment by heavysixer** [comment]
Ok I am able to recreate this error on your codebase. I will debug this further. Sorry again for blowing up the build.

**Comment by eee-c** [comment]
I bumped the Angular dependency to 1.3 and the old solution still works -- both the Karma tests and the test page.

FWIW, I start a Python simple http server in the root of the repository `python -m SimpleHTTPServer 8000` then access the test page at http://localhost:8000/. You should be able to type a number into the `<input>` field (in a Polymer) and see the result double below (in the Angular app).

**Comment by heavysixer** [comment]
Yeah I am obviously stupid, I am going to have to look at my full project where I am using the modified code and see why it works there.

Thanks again, sorry for the hassle. Yeah open source!
Mark

**Comment by eee-c** [comment]
No worries at all! I have gaps in my Angular so I am always eager to pick up new ideas and better approaches. I'll definitely pull in the on-destroy code -- that just makes sense.

I think your version is missing something from 0ff8f57b, which added support for object binding (e.g. `my.answer`) in Angular. Specifically, inside your observer, this line seems similar to the object binding code from the original:

```
              angular.forEach(stored, function(key) {
```

But it is iterating over a string -- the attribute name. If I print it to the console for the test page, `stored` is `"double"` and `key` is `"d"` on the first loop, `"o"` on the second loop, `"u"` on the third and so on. It never finds anything in the angular scope (since it ought to be trying to find `double` or `my.answer`), which is (I think) why it's not working.

Dunno if that makes sense or not.

Anyway, I'll prolly pull in the on-destroy and leave it at that for now. If you figure it out, do let me know. Thanks!

**Pull request merged**
